In [ ]:
import numpy as np
nums_list = [10, 12, 14, 16, 20]
nums_array = np.array(nums_list)
type(nums_array)

numpy.ndarray

In [ ]:
row1 = [10, 12, 13]
row2 = [45, 32, 16]
row3 = [45, 32, 16]

nums_2d = np.array([row1, row2, row3])
nums_2d.shape

(3, 3)

In [ ]:
nums_arr = np.arange(5, 11)
print(nums_arr)

[ 5  6  7  8  9 10]


In [ ]:
nums_arr = np.arange(5, 12, 2)
print(nums_arr)

[ 5  7  9 11]


In [ ]:
ones_array = np.ones(6)
print(ones_array)

[1. 1. 1. 1. 1. 1.]


In [ ]:
ones_array = np.ones((6, 4))
print(ones_array)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
zeros_array = np.zeros(6)
print(zeros_array)

[0. 0. 0. 0. 0. 0.]


In [ ]:
zeros_array = np.zeros((6, 4))
print(zeros_array)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
eyes_array = np.eye(5)
print(eyes_array)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [ ]:
uniform_random = np.random.rand(4, 5)
print(uniform_random)

[[0.30823859 0.58902804 0.21678881 0.74910001 0.61722336]
 [0.10701177 0.74621524 0.79606849 0.09183181 0.52607054]
 [0.89417518 0.2798246  0.23603011 0.6286778  0.57884214]
 [0.22497576 0.76287218 0.7622352  0.04889163 0.92878863]]


In [ ]:
normal_random = np.random.randn(4, 5)
print(normal_random)

[[ 1.5711391   0.42718391  0.96686428 -0.0129171  -1.51030147]
 [-1.57478256 -0.62430576  0.19730946 -1.73503891  0.49603213]
 [ 0.58105521 -0.64743919 -0.20520423  0.44348931  0.63734019]
 [-0.5285281  -0.11808534  0.29437209  3.05190336  0.20911256]]


In [ ]:
integer_random = np.random.randint(10, 50, 5)
print(integer_random)

[19 40 41 28 37]


In [ ]:
uniform_random = np.random.rand(4, 6)
uniform_random = uniform_random.reshape(3, 8)
print(uniform_random)

[[0.77858582 0.22951414 0.05562707 0.34039158 0.29475846 0.69147033
  0.19767113 0.53442222]
 [0.96785506 0.73540671 0.93859539 0.8491346  0.87485941 0.87265809
  0.16986728 0.62446688]
 [0.97613759 0.15762944 0.71135281 0.87792847 0.45350947 0.81283863
  0.72172944 0.93824012]]


In [ ]:
s = np.arange(1, 11)
print(s)

[ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
print(s[1])

2


In [ ]:
print(s[1:9])

[2 3 4 5 6 7 8 9]


In [ ]:
print(s[:5])
print(s[5:])

[1 2 3 4 5]
[ 6  7  8  9 10]


In [ ]:
row1 = [10, 12, 13]
row2 = [45, 32, 16]
row3 = [45, 32, 16]

nums_2d = np.array([row1, row2, row3])
print(nums_2d[:2, :])

[[10 12 13]
 [45 32 16]]


In [ ]:
row1 = [10, 12, 13]
row2 = [45, 32, 16]
row3 = [45, 32, 16]

nums_2d = np.array([row1, row2, row3])
print(nums_2d[:, :2])

[[10 12]
 [45 32]
 [45 32]]


In [ ]:
row1 = [10, 12, 13]
row2 = [45, 32, 16]
row3 = [45, 32, 16]

nums_2d = np.array([row1, row2, row3])
print(nums_2d[1:, 1:])

[[32 16]
 [32 16]]


In [ ]:
nums = [10, 20, 30, 40, 50]
np_sqr = np.sqrt(nums)
print(np_sqr)

[3.16227766 4.47213595 5.47722558 6.32455532 7.07106781]


In [ ]:
nums = [10, 20, 30, 40, 50]
np_log = np.log(nums)
print(np_log)

[2.30258509 2.99573227 3.40119738 3.68887945 3.91202301]


In [ ]:
nums = [10, 20, 30, 40, 50]
np_exp = np.exp(nums)
print(np_exp)

[2.20264658e+04 4.85165195e+08 1.06864746e+13 2.35385267e+17
 5.18470553e+21]


In [ ]:
nums = [10, 20, 30, 40, 50]
np_sine = np.sin(nums)
print(np_sine)

nums = [10, 20, 30, 40, 50]
np_cos = np.cos(nums)
print(np_cos)

[-0.54402111  0.91294525 -0.98803162  0.74511316 -0.26237485]
[-0.83907153  0.40808206  0.15425145 -0.66693806  0.96496603]


In [ ]:
A = np.random.randn(4, 5)

B = np.random.randn(5, 4)

Z = np.dot(A, B)

print(Z)

[[-0.12394191 -0.32305389  0.97505212  1.51234452]
 [-0.35585743 -2.02301904  1.15495457  2.77801263]
 [ 0.34519409 -0.76067798  0.79785627  0.79895546]
 [-5.16300663  1.08159722 -2.31598936 -0.5409981 ]]


In [ ]:
row1 = [10, 12, 13]
row2 = [45, 32, 16]
row3 = [45, 32, 16]

nums_2d = np.array([row1, row2, row3])
multiply = np.multiply(nums_2d, nums_2d)
print(multiply)

[[ 100  144  169]
 [2025 1024  256]
 [2025 1024  256]]


In [ ]:
row1 = [1, 2, 3]
row2 = [4, 5, 7]
row3 = [7, 8, 9]

nums_2d = np.array([row1, row2, row3])

inverse = np.linalg.inv(nums_2d)
print(inverse)

[[-1.83333333  1.         -0.16666667]
 [ 2.16666667 -2.          0.83333333]
 [-0.5         1.         -0.5       ]]


In [ ]:
row1 = [1, 2, 3]
row2 = [4, 5, 6]
row3 = [7, 8, 9]

nums_2d = np.array([row1, row2, row3])

determinant = np.linalg.det(nums_2d)
print(determinant)

0.0


In [ ]:
row1 = [1, 2, 3]
row2 = [4, 5, 6]
row3 = [7, 8, 9]

nums_2d = np.array([row1, row2, row3])

trace = np.trace(nums_2d)
print(trace)

15


**CHAPTER 4**

In [ ]:
import pandas as pd
titanic_data = pd.read_csv(r"/content/drive/MyDrive/titanic.csv")
titanic_data.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [ ]:
titanic_pclass1 = (titanic_data.Pclass == 1)
titanic_pclass1

0      False
1       True
2      False
3       True
4      False
       ...  
886    False
887     True
888    False
889     True
890    False
Name: Pclass, Length: 891, dtype: bool

In [ ]:
titanic_pclass1_data = titanic_data[titanic_pclass1]
titanic_pclass1_data.head()

PassengerId  Survived  Pclass  \
1             2         1       1   
3             4         1       1   
6             7         0       1   
11           12         1       1   
23           24         1       1   

                                                 Name     Sex   Age  SibSp  \
1   Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
3        Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
6                             McCarthy, Mr. Timothy J    male  54.0      0   
11                           Bonnell, Miss. Elizabeth  female  58.0      0   
23                       Sloper, Mr. William Thompson    male  28.0      0   

    Parch    Ticket     Fare Cabin Embarked  
1       0  PC 17599  71.2833   C85        C  
3       0    113803  53.1000  C123        S  
6       0     17463  51.8625   E46        S  
11      0    113783  26.5500  C103        S  
23      0    113788  35.5000    A6        S

In [ ]:
ages = [20, 21, 22]
age_dataset = titanic_data[titanic_data["Age"].isin(ages)]
age_dataset.head()

PassengerId  Survived  Pclass                            Name     Sex  \
0             1         0       3         Braund, Mr. Owen Harris    male   
12           13         0       3  Saundercock, Mr. William Henry    male   
37           38         0       3        Cann, Mr. Ernest Charles    male   
51           52         0       3    Nosworthy, Mr. Richard Cater    male   
56           57         1       2               Rugg, Miss. Emily  female   

     Age  SibSp  Parch      Ticket   Fare Cabin Embarked  
0   22.0      1      0   A/5 21171   7.25   NaN        S  
12  20.0      0      0   A/5. 2151   8.05   NaN        S  
37  21.0      0      0  A./5. 2152   8.05   NaN        S  
51  21.0      0      0  A/4. 39886   7.80   NaN        S  
56  21.0      0      0  C.A. 31026  10.50   NaN        S

In [ ]:
ageclass_dataset = titanic_data[titanic_data["Age"].isin(ages) & (titanic_data["Pclass"] == 1)]
ageclass_dataset.head()

PassengerId  Survived  Pclass                                Name  \
102          103         0       1           White, Mr. Richard Frasar   
151          152         1       1   Pears, Mrs. Thomas (Edith Wearne)   
356          357         1       1         Bowerman, Miss. Elsie Edith   
373          374         0       1                 Ringhini, Mr. Sante   
539          540         1       1  Frolicher, Miss. Hedwig Margaritha   

        Sex   Age  SibSp  Parch    Ticket      Fare Cabin Embarked  
102    male  21.0      0      1     35281   77.2875   D26        S  
151  female  22.0      1      0    113776   66.6000    C2        S  
356  female  22.0      0      1    113505   55.0000   E33        S  
373    male  22.0      0      0  PC 17760  135.6333   NaN        C  
539  female  22.0      0      2     13568   49.5000   B39        C

In [ ]:
titanic_data_filter = titanic_data.filter(["Name", "Sex", "Age"])
titanic_data_filter.head()

Name     Sex   Age
0                            Braund, Mr. Owen Harris    male  22.0
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0
2                             Heikkinen, Miss. Laina  female  26.0
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0
4                           Allen, Mr. William Henry    male  35.0

In [ ]:
titanic_data_filter = titanic_data.drop(["Name", "Sex", "Age"], axis = 1)
titanic_data_filter.head()

PassengerId  Survived  Pclass  SibSp  Parch            Ticket     Fare  \
0            1         0       3      1      0         A/5 21171   7.2500   
1            2         1       1      1      0          PC 17599  71.2833   
2            3         1       3      0      0  STON/O2. 3101282   7.9250   
3            4         1       1      1      0            113803  53.1000   
4            5         0       3      0      0            373450   8.0500   

  Cabin Embarked  
0   NaN        S  
1   C85        C  
2   NaN        S  
3  C123        S  
4   NaN        S

In [ ]:
print(titanic_pclass1_data.shape)

titanic_pclass2_data = titanic_data[titanic_data.Pclass == 2]
print(titanic_pclass2_data.shape)

(216, 12)
(184, 12)


In [ ]:
final_data = titanic_pclass1_data.append(titanic_pclass2_data, ignore_index = True)
print(final_data.shape)

(400, 12)


<ipython-input-58-261338199d5b>:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_data = titanic_pclass1_data.append(titanic_pclass2_data, ignore_index = True)


In [ ]:
final_data = pd.concat([titanic_pclass1_data, titanic_pclass2_data])
print(final_data.shape)

(400, 12)


In [ ]:
df1 = final_data[:200]
print(df1.shape)
df2 = final_data[200:]
print(df2.shape)

final_data2 = pd.concat([df1, df2], axis = 1, ignore_index = True)
print(final_data2.shape)

(200, 12)
(200, 12)
(400, 24)


In [ ]:
age_sorted_data = titanic_data.sort_values(by=['Age'])
age_sorted_data.head()

PassengerId  Survived  Pclass                             Name     Sex  \
803          804         1       3  Thomas, Master. Assad Alexander    male   
755          756         1       2        Hamalainen, Master. Viljo    male   
644          645         1       3           Baclini, Miss. Eugenie  female   
469          470         1       3    Baclini, Miss. Helene Barbara  female   
78            79         1       2    Caldwell, Master. Alden Gates    male   

      Age  SibSp  Parch  Ticket     Fare Cabin Embarked  
803  0.42      0      1    2625   8.5167   NaN        C  
755  0.67      1      1  250649  14.5000   NaN        S  
644  0.75      2      1    2666  19.2583   NaN        C  
469  0.75      2      1    2666  19.2583   NaN        C  
78   0.83      0      2  248738  29.0000   NaN        S

In [ ]:
age_sorted_data = titanic_data.sort_values(by=['Age'], ascending = False)
age_sorted_data.head()

PassengerId  Survived  Pclass                                  Name  \
630          631         1       1  Barkworth, Mr. Algernon Henry Wilson   
851          852         0       3                   Svensson, Mr. Johan   
493          494         0       1               Artagaveytia, Mr. Ramon   
96            97         0       1             Goldschmidt, Mr. George B   
116          117         0       3                  Connors, Mr. Patrick   

      Sex   Age  SibSp  Parch    Ticket     Fare Cabin Embarked  
630  male  80.0      0      0     27042  30.0000   A23        S  
851  male  74.0      0      0    347060   7.7750   NaN        S  
493  male  71.0      0      0  PC 17609  49.5042   NaN        C  
96   male  71.0      0      0  PC 17754  34.6542    A5        C  
116  male  70.5      0      0    370369   7.7500   NaN        Q

In [ ]:
age_sorted_data = titanic_data.sort_values(by=['Age', 'Fare'], ascending = False)
age_sorted_data.head()

PassengerId  Survived  Pclass                                  Name  \
630          631         1       1  Barkworth, Mr. Algernon Henry Wilson   
851          852         0       3                   Svensson, Mr. Johan   
493          494         0       1               Artagaveytia, Mr. Ramon   
96            97         0       1             Goldschmidt, Mr. George B   
116          117         0       3                  Connors, Mr. Patrick   

      Sex   Age  SibSp  Parch    Ticket     Fare Cabin Embarked  
630  male  80.0      0      0     27042  30.0000   A23        S  
851  male  74.0      0      0    347060   7.7750   NaN        S  
493  male  71.0      0      0  PC 17609  49.5042   NaN        C  
96   male  71.0      0      0  PC 17754  34.6542    A5        C  
116  male  70.5      0      0    370369   7.7500   NaN        Q

In [ ]:
updated_class = titanic_data.Pclass.apply(lambda x : x + 2)
updated_class.head()

0    5
1    3
2    5
3    3
4    5
Name: Pclass, dtype: int64

In [ ]:
def mult(x):
    return x * 2

updated_class = titanic_data.Pclass.apply(mult)
updated_class.head()

0    6
1    2
2    6
3    2
4    6
Name: Pclass, dtype: int64

In [ ]:
import matplotlib.pyplot as plt
import seaborn as sns


flights_data = sns.load_dataset('flights')

flights_data.head()

year month  passengers
0  1949   Jan         112
1  1949   Feb         118
2  1949   Mar         132
3  1949   Apr         129
4  1949   May         121

In [ ]:
flights_data_pivot = flights_data.pivot_table(index = 'month', columns = 'year', values = 'passengers')
flights_data_pivot.head()

year   1949  1950  1951  1952  1953  1954  1955  1956  1957  1958  1959  1960
month                                                                        
Jan     112   115   145   171   196   204   242   284   315   340   360   417
Feb     118   126   150   180   196   188   233   277   301   318   342   391
Mar     132   141   178   193   236   235   267   317   356   362   406   419
Apr     129   135   163   181   235   227   269   313   348   348   396   461
May     121   125   172   183   229   234   270   318   355   363   420   472

In [ ]:
pd.crosstab(titanic_data.Pclass, titanic_data.Age, margins = True)

Age     0.42  0.67  0.75  0.83  0.92  1.0  2.0  3.0  4.0  5.0  ...  63.0  \
Pclass                                                         ...         
1          0     0     0     0     1    0    1    0    1    0  ...     1   
2          0     1     0     2     0    2    2    3    2    1  ...     0   
3          1     0     2     0     0    5    7    3    7    3  ...     1   
All        1     1     2     2     1    7   10    6   10    4  ...     2   

Age     64.0  65.0  66.0  70.0  70.5  71.0  74.0  80.0  All  
Pclass                                                       
1          2     2     0     1     0     2     0     1  186  
2          0     0     1     1     0     0     0     0  173  
3          0     1     0     0     1     0     1     0  355  
All        2     3     1     2     1     2     1     1  714  

[4 rows x 89 columns]

In [ ]:
import numpy as np
titanic_data.Fare = np.where(titanic_data.Age > 20, titanic_data.Fare +5, titanic_data.Fare)

titanic_data.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171  12.2500   NaN        S  
1      0          PC 17599  76.2833   C85        C  
2      0  STON/O2. 3101282  12.9250   NaN        S  
3      0            113803  58.1000  C123        S  
4      0            373450  13.0500   NaN        S